import React from 'react';
import { InstrumentLayer, TrackMetadata } from '../types';
import { Button } from './Button';

interface StudioEditorProps {
  metadata: TrackMetadata;
  layers: InstrumentLayer[];
  onToggleLayer: (id: string) => void;
  onVolumeChange: (id: string, vol: number) => void;
  isPlaying: boolean;
}

export const StudioEditor: React.FC<StudioEditorProps> = ({ 
  metadata, 
  layers, 
  onToggleLayer, 
  onVolumeChange,
  isPlaying 
}) => {
  
  return (
    <div className="bg-zinc-950 rounded-xl border border-zinc-800 overflow-hidden shadow-2xl mt-4">
      {/* Studio Header */}
      <div className="bg-zinc-900 px-4 py-3 border-b border-zinc-800 flex justify-between items-center">
        <div className="flex items-center gap-2">
           <span className={`w-2 h-2 rounded-full ${isPlaying ? 'bg-green-500 animate-pulse' : 'bg-red-500'}`}></span>
           <span className="text-xs font-mono text-zinc-400 uppercase">AI BAND COMPOSER</span>
        </div>
        <div className="text-right">
           <div className="text-xs font-bold text-white tracking-wider">{metadata.genre.toUpperCase()}</div>
           <div className="text-[10px] text-zinc-500 font-mono">{metadata.bpm} BPM • {metadata.key}</div>
        </div>
      </div>

      <div className="p-0">
        {layers.map((layer, index) => (
          <div 
            key={layer.id} 
            className={`border-b border-zinc-800/50 p-4 transition-colors ${
              layer.type === 'user' ? 'bg-indigo-900/10' : 'bg-zinc-900/30'
            } ${!layer.isActive ? 'opacity-50 grayscale' : ''}`}
          >
            <div className="flex items-center gap-4">
              {/* Mute/Active Toggle */}
              <button 
                onClick={() => onToggleLayer(layer.id)}
                className={`w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold transition-all ${
                  layer.isActive 
                    ? layer.type === 'user' ? 'bg-indigo-500 text-white' : 'bg-emerald-600 text-white'
                    : 'bg-zinc-700 text-zinc-400'
                }`}
              >
                {layer.name.charAt(0)}
              </button>

              {/* Track Info */}
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2">
                  <span className="text-sm font-semibold text-white truncate">{layer.name}</span>
                  {layer.type === 'user' && (
                    <span className="text-[10px] px-1.5 py-0.5 rounded bg-indigo-500/20 text-indigo-300 border border-indigo-500/30">
                      YOUR UPLOAD
                    </span>
                  )}
                  {layer.type === 'ai' && (
                    <span className="text-[10px] px-1.5 py-0.5 rounded bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
                      AI GENERATED
                    </span>
                  )}
                </div>
                <p className="text-xs text-zinc-500 truncate mt-0.5">{layer.description}</p>
              </div>

              {/* Volume Slider */}
              <div className="w-24 hidden md:block">
                <input 
                  type="range" 
                  min="0" max="100" 
                  value={layer.volume}
                  onChange={(e) => onVolumeChange(layer.id, parseInt(e.target.value))}
                  className="w-full h-1 bg-zinc-700 rounded-lg appearance-none cursor-pointer accent-zinc-400"
                />
              </div>

              {/* Visual Activity (Fake) */}
              <div className="w-16 h-8 flex items-center gap-0.5">
                 {[1,2,3,4,5].map(i => (
                   <div 
                     key={i} 
                     className={`w-2 bg-zinc-600 rounded-sm transition-all duration-75`}
                     style={{ 
                       height: layer.isActive && isPlaying ? `${Math.random() * 100}%` : '20%',
                       opacity: layer.isActive ? 1 : 0.3
                     }}
                   />
                 ))}
              </div>
            </div>
          </div>
        ))}
      </div>
      
      <div className="p-4 bg-zinc-900 border-t border-zinc-800 text-center">
         <p className="text-xs text-zinc-500">
           *Audio preview simulates the full mix. In a real backend implementation, these layers would be separate audio files generated by a model like MusicLM.
         </p>
      </div>
    </div>
  );
};
